module.exports = {
  sidebar: [
    {
      type: "doc",
      id: "intro"
    },
    {
      type: "autogenerated",
      dirName: "website"
    },
    {
      type: "category",
      label: "Development",
      items: [
        {
          type: "autogenerated",
          dirName: "development"
        }
      ]
    }
  ]
};
