module.exports = {
  sidebar: [
    {
      type: "doc",
      id: "intro"
    },
    {
      type: "autogenerated",
      dirName: "website"
    }
  ],
  development: [
    {
      type: "autogenerated",
      dirName: "development"
    }
  ]
};
